[package]
name = "solutions_2024"
version = "0.1.0"
edition = "2024"

[dependencies]
common = {path = "../common"}
fxhash = "0.2.1"
itertools = "*"
nalgebra = "0.33.2"
nom = "7"
rayon = "1.10.0"
regex = "1.11.1"
rstest = "0.23.0"
