[package]
edition = "2021"
name = "solutions_2022"
version = "0.1.0"

[dependencies]
common = {path = "../common"}
crossterm = "0.25"
itertools = "0.10"
nom = "7"
num = "0.4"
petgraph = "0.6"
rayon = "1.6"
regex = "1"

[dev-dependencies]
rstest = "0.16"
